#!/bin/bash
#pwd
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd "${DIR}"
echo 'Clearing Debug folder' &&
rm bin/Debug/Solve.exe
echo 'Building project'
msbuild SharpSolver.sln
echo 'Executing Solve program'
mono bin/Debug/SharpSolver.exe
